# -*- coding: utf-8 -*-
"""Bug Tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zrMhufB0q5XwuxU66SHs5AZ83R66HpQ
"""

import os
import time

def file_bug(id):
    print("**********")
    print("FILING A BUG")
    print("***********")

    current_time = time.ctime()
    name = input("Enter your name: ")
    filename = f"{name}{id}.txt"
    title = input("Enter bug title: ")
    with open(filename, "w") as file:
        file.write(f"DATE AND TIME: {current_time}\n\n")
        file.write(f"BUG ID: {id}\n")
        file.write(f"BUG FILED BY: {name}\n")
        file.write(f"BUG TITLE: {title}\n")
        bugtype = input("Enter bug type: ")
        file.write(f"TYPE OF BUG: {bugtype}\n")
        priority = choose_priority()
        file.write(f"BUG PRIORITY: {priority}\n")
        bugdescription = input("Enter the bug description: ")
        file.write(f"BUG DESCRIPTION: {bugdescription}\n")
        status = choose_status()
        file.write(f"DATE AND TIME: {current_time}\n\n")
        file.write(f"BUG STATUS: {status}\n\n")
    print(f"Bug filed successfully. Filename: {filename}")

def update_bug_description(filename):
    new_description = input("Enter the new bug description: ")
    update_file(filename, "BUG DESCRIPTION:", new_description)
    print("Bug description updated successfully.")

def update_bug_title(filename):
    new_title = input("Enter the new bug title: ")
    update_file(filename, "BUG TITLE:", new_title)
    print("Bug title updated successfully.")

def update_bug_priority(filename):
    new_priority = choose_priority()
    update_file(filename, "BUG PRIORITY:", new_priority)
    print("Bug priority updated successfully.")


def choose_priority():
    print("Bug Priority:")
    print("1. Low")
    print("2. Medium")
    print("3. High")
    choice = int(input("Enter priority level: "))
    if choice == 1:
        return "Low"
    elif choice == 2:
        return "Medium"
    elif choice == 3:
        return "High"
    else:
        print("Invalid choice")
        return "Unknown"

def choose_status():
    print("Status of bug:")
    print("1. NOT YET ASSIGNED")
    print("2. IN PROCESS")
    print("3. FIXED")
    print("4. DELIVERED")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        return "NOT YET ASSIGNED"
    elif choice == 2:
        return "IN PROCESS"
    elif choice == 3:
        return "FIXED"
    elif choice == 4:
        return "DELIVERED"
    else:
        print("Invalid choice")
        return "Unknown"

def change_status():
    print("*************")
    print("Change status")
    print("**************")
    filename = input("Enter file name: ")
    new_status = choose_status()
    update_file(filename, "BUG STATUS:", new_status)
    print("Status updated successfully.")

def update_file(filename, field, new_content):
    if not os.path.exists(filename):
        print("Bug file not found.")
        return
    with open(filename, "r") as file:
        lines = file.readlines()
    with open(filename, "w") as file:
        field_found = False
        for line in lines:
            if line.startswith(field):

                file.write(f"{field} {new_content}\n")
                field_found = True
            else:
                file.write(line)
        if not field_found:

            file.write(f"{field} {new_content}\n")


def report():
    print("**********")
    print("REPORT")
    print("**********")
    filename = input("Enter file name: ")
    with open(filename, "r") as file:
        print(file.read())

def delete_bug():
    print("*************")
    print("Delete Bug")
    print("**************")
    filename = input("Enter file name: ")
    if os.path.exists(filename):
        os.remove(filename)
        print(f"Bug file '{filename}' deleted successfully.")
    else:
        print("Bug file not found.")

def main():
    print("***************")
    print("BUG TRACKING SYSTEM")
    print("***************")
    id = 0
    while True:
        print("\n1. FILE A NEW BUG")
        print("2. UPDATE THE STATUS OF THE BUG")
        print("3. GET BUG REPORT")
        print("4. DELETE A BUG")
        print("5. UPDATE BUG DESCRIPTION")
        print("6. UPDATE BUG TITLE")
        print("7. UPDATE BUG PRIORITY")
        print("8. EXIT")

        number = int(input("\nENTER YOUR CHOICE: "))

        if number == 1:
            id += 1
            file_bug(id)
        elif number == 2:
            change_status()
        elif number == 3:
            report()
        elif number == 4:
            delete_bug()
        elif number == 5:
            filename = input("Enter the bug file name to update description: ")
            update_bug_description(filename)
        elif number == 6:
            filename = input("Enter the bug file name to update title: ")
            update_bug_title(filename)
        elif number == 7:
            filename = input("Enter the bug file name to update priority: ")
            update_bug_priority(filename)
        elif number == 8:
            print("Exiting Bug Tracking System. Goodbye!")
            break
        else:
            print("Invalid entry")

if __name__ == "__main__":
    main()